export const wordList = {
  generalKnowledge: [
    { word: "capital", hint: "The main city of a country" },
    { word: "continent", hint: "A large landmass on Earth" },
    { word: "ocean", hint: "A vast body of saltwater" },
    { word: "monarchy", hint: "A government ruled by a king or queen" },
    { word: "democracy", hint: "A system where people elect leaders" },
    { word: "invention", hint: "A new creation or discovery" },
    { word: "currency", hint: "The money used in a country" },
    { word: "festival", hint: "A celebration of culture or tradition" },
    { word: "mythology", hint: "Ancient stories explaining natural events" },
    { word: "astronaut", hint: "A person who travels in space" },
    { word: "dinosaur", hint: "A prehistoric reptile species" },
    { word: "volcano", hint: "A mountain that erupts with lava" },
    { word: "fossil", hint: "Preserved remains of ancient organisms" },
    { word: "gravity", hint: "The force that pulls objects toward Earth" },
    { word: "climate", hint: "The long-term weather patterns in a region" },
    { word: "telescope", hint: "An instrument used to view distant objects" },
    { word: "equator", hint: "An imaginary line dividing the Earth" },
    { word: "oxygen", hint: "A gas essential for human survival" },
    { word: "galaxy", hint: "A vast collection of stars and planets" },
    { word: "pyramid", hint: "A triangular ancient Egyptian structure" },
    { word: "solar", hint: "Relating to the sun" },
    { word: "orbit", hint: "The path a planet follows around a star" },
    { word: "longitude", hint: "Imaginary lines measuring east and west" },
    { word: "latitude", hint: "Imaginary lines measuring north and south" },
    { word: "oxygen", hint: "Gas necessary for breathing" },
    { word: "ecosystem", hint: "A community of living organisms" },
    { word: "mammal", hint: "A warm-blooded animal with fur" },
    { word: "reptile", hint: "A cold-blooded animal with scales" },
    { word: "pollution", hint: "Harmful substances in the environment" },
    { word: "meteor", hint: "A rock from space that enters Earth's atmosphere" },
    { word: "tsunami", hint: "A large ocean wave caused by an earthquake" },
  ],
  programming: [
    { word: "typescript", hint: "A typed superset of JavaScript" },
    { word: "javascript", hint: "A scripting language for the web" },
    { word: "programming", hint: "Writing code to create software" },
    { word: "developer", hint: "Someone who creates software" },
    { word: "interface", hint: "A contract defining object structure" },
    { word: "component", hint: "A reusable piece of UI" },
    { word: "algorithm", hint: "A step-by-step procedure for solving a problem" },
    { word: "variable", hint: "A storage location identified by a name" },
    { word: "function", hint: "A block of code designed to perform a task" },
    { word: "object", hint: "An instance of a class" },
    { word: "class", hint: "A blueprint for creating objects" },
    { word: "loop", hint: "A control structure that repeats a block of code" },
    { word: "recursion", hint: "A function calling itself to solve a problem" },
    { word: "closure", hint: "A function with access to its outer scope" },

    // Computer Science Principles
    { word: "inheritance", hint: "A mechanism for basing a class on another class" },
    { word: "encapsulation", hint: "The bundling of data with related methods" },
    { word: "polymorphism", hint: "Providing a single interface for multiple data types" },
    { word: "abstraction", hint: "Hiding complex reality while exposing only necessary parts" },
    { word: "syntax", hint: "Rules defining the structure of code" },
    { word: "debugging", hint: "Finding and fixing errors in software" },
    { word: "compilation", hint: "Translating source code into executable code" },
    { word: "runtime", hint: "The period when a program is executing" },
    { word: "data structure", hint: "A way of organizing and storing data" },
    { word: "big o notation", hint: "Describes the efficiency of an algorithm" },
    { word: "hashing", hint: "Converting data into a fixed-size value" },
    { word: "binary search", hint: "An efficient searching algorithm for sorted lists" },
    { word: "stack", hint: "A Last-In-First-Out (LIFO) data structure" },
    { word: "queue", hint: "A First-In-First-Out (FIFO) data structure" },

    // Software Development Concepts
    { word: "framework", hint: "A platform for developing applications" },
    { word: "library", hint: "A collection of reusable code modules" },
    { word: "module", hint: "A self-contained piece of code" },
    { word: "package", hint: "A bundle of software that can be installed" },
    { word: "dependency", hint: "Software required by another program" },
    { word: "repository", hint: "A central location where code is stored" },
    { word: "commit", hint: "A record of changes made to a repository" },
    { word: "branch", hint: "A parallel version of a repository" },
    { word: "merge", hint: "Combining changes from different branches" },
    { word: "pull request", hint: "A request to merge code changes into a branch" },
    { word: "version control", hint: "Tracking changes in code over time" },

    // Software Engineering & Testing
    { word: "unit test", hint: "A test for a single function or module" },
    { word: "integration test", hint: "A test for multiple units working together" },
    { word: "end-to-end test", hint: "A test covering the entire application" },
    { word: "refactoring", hint: "Restructuring code without changing its behavior" },
    { word: "continuous integration", hint: "Merging code changes frequently" },
    { word: "continuous deployment", hint: "Automatically deploying successful code changes" },
    { word: "agile", hint: "A flexible and iterative software development approach" },
    { word: "scrum", hint: "A framework for managing agile development" },
    { word: "kanban", hint: "A visual method for tracking work progress" },
    { word: "design pattern", hint: "A reusable solution to common software design problems" },

    // Advanced Topics
    { word: "websocket", hint: "A protocol for real-time communication" },
    { word: "graphql", hint: "A query language for APIs" },
    { word: "restful", hint: "A style of web API architecture" },
    { word: "docker", hint: "A platform for containerizing applications" },
    { word: "kubernetes", hint: "A system for managing containerized applications" },
    { word: "serverless", hint: "A cloud execution model without managing servers" },
    { word: "microservices", hint: "An architecture where services are independent and modular" },
    { word: "machine learning", hint: "A field of AI that allows systems to learn from data" },
    { word: "blockchain", hint: "A decentralized and secure digital ledger" },
  ],

  science: [
    { word: "biology", hint: "The study of living organisms and life processes" },
    { word: "chemistry", hint: "The study of substances, their properties, and reactions" },
    { word: "physics", hint: "The study of matter, energy, and forces" },
    { word: "mathematics", hint: "The study of numbers, patterns, and logical structures" },
    { word: "astronomy", hint: "The study of celestial objects and the universe" },
    { word: "geology", hint: "The study of Earth's structure, history, and processes" },
    { word: "meteorology", hint: "The study of weather, climate, and atmospheric phenomena" },
    { word: "oceanography", hint: "The study of the ocean's physical, chemical, and biological properties" },
    { word: "ecology", hint: "The study of interactions between organisms and their environment" },
    { word: "genetics", hint: "The study of heredity and variation in living organisms" },
    { word: "botany", hint: "The study of plants, their structure, and functions" },
    { word: "zoology", hint: "The study of animals, their behavior, and classification" },
    { word: "microbiology", hint: "The study of microscopic organisms like bacteria and viruses" },
    { word: "biochemistry", hint: "The study of chemical processes in living organisms" },
    { word: "thermodynamics", hint: "The study of heat, energy, and work" },
    { word: "astrophysics", hint: "The study of physics in space and celestial objects" },
    { word: "paleontology", hint: "The study of fossils and ancient life forms" },
    { word: "seismology", hint: "The study of earthquakes and seismic waves" },
    { word: "environmental science", hint: "The study of Earth's natural systems and human impact" },
    { word: "nanotechnology", hint: "The study of materials at an atomic and molecular scale" },
  ],
  socialSciences: [
    { word: "philosophy", hint: "The study of fundamental questions about existence, ethics, and knowledge" },
    { word: "psychology", hint: "The study of human thoughts, emotions, and behavior" },
    { word: "sociology", hint: "The study of society, social relationships, and institutions" },
    { word: "economics", hint: "The study of production, distribution, and consumption of goods and services" },
    { word: "politics", hint: "The study of governance, policies, and power structures" },
    { word: "history", hint: "The study of past events, civilizations, and their impact" },
    { word: "geography", hint: "The study of Earth's landscapes, environments, and human interactions" },
    { word: "linguistics", hint: "The study of languages, their structure, and evolution" },
    { word: "anthropology", hint: "The study of human cultures, societies, and evolution" },
    { word: "archaeology", hint: "The study of ancient human history through artifacts and ruins" },
    { word: "demography", hint: "The study of populations, birth rates, and migration" },
    { word: "criminology", hint: "The study of crime, law enforcement, and criminal behavior" },
    { word: "ethnography", hint: "The study of cultures through firsthand observation" },
    { word: "social psychology", hint: "The study of how people influence and interact with each other" },
    { word: "political science", hint: "The study of political systems, ideologies, and governance" },
    { word: "international relations", hint: "The study of diplomacy and global affairs" },
    { word: "public administration", hint: "The study of government policies and management" },
    { word: "cultural studies", hint: "The study of traditions, customs, and societal values" },
    { word: "social work", hint: "The study of helping individuals and communities improve well-being" },
    { word: "media studies", hint: "The study of communication, journalism, and mass media" },
    { word: "urban studies", hint: "The study of cities, development, and urban life" },
    { word: "gender studies", hint: "The study of gender roles, identity, and social structures" },
    { word: "human geography", hint: "The study of how humans interact with their environment" },
    { word: "sociolinguistics", hint: "The study of language in social and cultural contexts" },
    { word: "behavioral economics", hint: "The study of psychology’s impact on economic decisions" },
    { word: "legal studies", hint: "The study of laws, legal systems, and justice" },
    { word: "development studies", hint: "The study of global development and socio-economic change" },
    { word: "public policy", hint: "The study of government decisions and societal impacts" },
  ],
  arts: [
    { word: "literature", hint: "Written artistic works, including poetry, novels, and essays" },
    { word: "painting", hint: "The art of applying pigment to a surface to create images" },
    { word: "sculpture", hint: "The process of shaping materials into three-dimensional forms" },
    { word: "music", hint: "The arrangement of sounds and rhythms into expressive compositions" },
    { word: "theater", hint: "The performance of plays, drama, and live storytelling" },
    { word: "cinema", hint: "The art of making films, using visuals and storytelling" },
    { word: "architecture", hint: "The design and construction of buildings and structures" },
    { word: "dance", hint: "Expressing emotions and ideas through rhythmic movement" },
    { word: "photography", hint: "Capturing images using a camera and creative techniques" },
    { word: "calligraphy", hint: "The art of beautiful and decorative handwriting" },
    { word: "graphic design", hint: "Visual communication through typography and imagery" },
    { word: "fashion design", hint: "Creating clothing, accessories, and wearable art" },
    { word: "opera", hint: "A theatrical performance combining music, singing, and drama" },
    { word: "illustration", hint: "Creating drawings or paintings to visually explain ideas" },
    { word: "animation", hint: "Bringing images to life through motion techniques" },
    { word: "printmaking", hint: "Creating art by transferring ink onto surfaces like paper" },
    { word: "mosaic", hint: "Artistic images created by arranging small colored pieces" },
    { word: "ceramics", hint: "Crafting objects from clay and firing them in a kiln" },
    { word: "textile art", hint: "Creating fabric-based works through weaving and embroidery" },
    { word: "digital art", hint: "Art created using computers and digital tools" },
    { word: "street art", hint: "Creative works displayed in public spaces, often graffiti" },
    { word: "performance art", hint: "Art expressed through live actions and interactions" },
    { word: "installation art", hint: "Large-scale artistic environments that engage viewers" },
    { word: "conceptual art", hint: "Art that emphasizes ideas over visual form" },
    { word: "modern art", hint: "Innovative artistic styles from the late 19th century onward" },
    { word: "baroque", hint: "A dramatic, ornate style of art from the 17th century" },
    { word: "surrealism", hint: "Art inspired by dreams and the subconscious mind" },
    { word: "impressionism", hint: "A painting style capturing light and movement" },
    { word: "cubism", hint: "Art that depicts objects from multiple angles at once" },
  ],
  sports: [
    // Team Sports
    { word: "soccer", hint: "Popular sport played with a round ball and goals" },
    { word: "basketball", hint: "Sport played with a hoop and a bouncing ball" },
    { word: "football", hint: "American sport with touchdowns and field goals" },
    { word: "baseball", hint: "Sport with bats, bases, and home runs" },
    { word: "hockey", hint: "Played on ice with a puck and sticks" },
    { word: "volleyball", hint: "Game where players hit a ball over a net" },
    { word: "rugby", hint: "Physical sport with a ball similar to football" },
    { word: "cricket", hint: "Bat-and-ball game popular in England and India" },
    { word: "handball", hint: "Sport where players throw a ball into a goal" },
    { word: "water polo", hint: "Team sport played in a swimming pool" },
  
    // Individual Sports
    { word: "tennis", hint: "Sport played with rackets and a net" },
    { word: "golf", hint: "Game where players hit a ball into holes" },
    { word: "boxing", hint: "Combat sport with gloves and a ring" },
    { word: "wrestling", hint: "Physical combat sport involving grappling" },
    { word: "swimming", hint: "Sport that involves racing in water" },
    { word: "cycling", hint: "Racing sport using bicycles" },
    { word: "badminton", hint: "Racket sport with a shuttlecock" },
    { word: "table tennis", hint: "Fast-paced version of tennis played on a table" },
    { word: "track and field", hint: "Athletics events including running and jumping" },
  
    // Racing Sports
    { word: "Formula 1", hint: "Fast-paced car racing sport" },
    { word: "motocross", hint: "Motorcycle racing on off-road tracks" },
    { word: "karting", hint: "Miniature car racing sport" },
    { word: "drag racing", hint: "Straight-line high-speed car racing" },
    { word: "marathon", hint: "Long-distance running event" },
    { word: "sprint", hint: "Short-distance high-speed running race" },
  
    // Extreme Sports
    { word: "surfing", hint: "Riding waves on a board" },
    { word: "skydiving", hint: "Jumping from a plane with a parachute" },
    { word: "bungee jumping", hint: "Jumping off a high place with a cord" },
    { word: "skateboarding", hint: "Sport involving tricks on a board with wheels" },
    { word: "snowboarding", hint: "Riding a board down a snowy slope" },
    { word: "rock climbing", hint: "Scaling cliffs or artificial walls" },
    { word: "parkour", hint: "Jumping, climbing, and vaulting through obstacles" },
  
    // Combat Sports & Martial Arts
    { word: "MMA", hint: "Mixed martial arts combat sport" },
    { word: "karate", hint: "Japanese martial art of striking" },
    { word: "judo", hint: "Grappling-based martial art from Japan" },
    { word: "taekwondo", hint: "Korean martial art focused on kicking" },
    { word: "kung fu", hint: "Traditional Chinese martial art" },
    { word: "muay thai", hint: "Thai combat sport using elbows and knees" },
    { word: "jiu-jitsu", hint: "Brazilian ground-fighting martial art" },
    { word: "kickboxing", hint: "Martial art combining punches and kicks" },
  
    // Olympic Sports
    { word: "gymnastics", hint: "Sport involving acrobatics and routines" },
    { word: "fencing", hint: "Sword fighting sport with protective gear" },
    { word: "archery", hint: "Sport involving shooting arrows" },
    { word: "rowing", hint: "Water sport involving boats and paddles" },
    { word: "equestrian", hint: "Sport involving horse riding" },
    { word: "weightlifting", hint: "Sport focused on lifting heavy weights" },
    { word: "triathlon", hint: "Race involving swimming, cycling, and running" },
  
    // Sports Terminology
    { word: "offside", hint: "Violation in soccer and hockey" },
    { word: "hat trick", hint: "Scoring three times in one game" },
    { word: "penalty", hint: "Punishment for a rule violation in sports" },
    { word: "touchdown", hint: "Scoring in American football" },
    { word: "home run", hint: "Baseball term for hitting the ball out of the field" },
    { word: "strike", hint: "Baseball term for a missed hit attempt" },
    { word: "dribble", hint: "Basketball term for bouncing the ball while moving" },
    { word: "dunk", hint: "Basketball move where the ball is slammed into the hoop" },
    { word: "serve", hint: "Tennis or volleyball action to start a play" },
    { word: "goal", hint: "Scoring in soccer and hockey" },
    { word: "red card", hint: "Soccer penalty for serious fouls" },
    { word: "corner kick", hint: "Soccer restart after the ball crosses the goal line" },
    { word: "slam dunk", hint: "Spectacular way to score in basketball" },
    { word: "knockout", hint: "Winning a boxing match by incapacitating an opponent" },
    { word: "foul", hint: "Breaking the rules in various sports" },
    { word: "overtime", hint: "Extra time in case of a tie" },
    { word: "world cup", hint: "Global soccer tournament held every four years" },
    { word: "grand slam", hint: "Winning all major titles in tennis or golf" },
  
    // Sports Events & Competitions
    { word: "Olympics", hint: "Global multi-sport event held every four years" },
    { word: "FIFA", hint: "Organization governing world soccer" },
    { word: "NBA", hint: "Professional basketball league in the USA" },
    { word: "NFL", hint: "Professional American football league" },
    { word: "UEFA", hint: "European soccer governing body" },
    { word: "Wimbledon", hint: "Famous tennis tournament in England" },
    { word: "Tour de France", hint: "Famous long-distance cycling race" },
    { word: "Super Bowl", hint: "Championship game in American football" },
    { word: "World Cup", hint: "Biggest international soccer tournament" },
    { word: "Formula One", hint: "Premier car racing championship" },
    { word: "US Open", hint: "Major tennis tournament in the United States" },
    { word: "Masters", hint: "Prestigious golf tournament" }
  ],
  
  engineering: [
    // Major Engineering Disciplines
    { word: "mechanical", hint: "Engineering of machines and tools" },
    { word: "electrical", hint: "Engineering of circuits and power" },
    { word: "civil", hint: "Engineering of buildings and infrastructure" },
    { word: "biomedical", hint: "Engineering applied to medicine" },
    { word: "robotics", hint: "Engineering of automated machines" },
    { word: "AI", hint: "Machines simulating human intelligence" },
    { word: "chemical", hint: "Engineering of chemical processes" },
    { word: "aerospace", hint: "Engineering of aircraft and spacecraft" },
    { word: "computer", hint: "Engineering of computers and software" },
    { word: "software", hint: "Engineering of programs and applications" },
    { word: "environmental", hint: "Engineering for environmental protection" },
    { word: "industrial", hint: "Engineering for optimizing systems" },
    { word: "nuclear", hint: "Engineering of nuclear energy and safety" },
    { word: "petroleum", hint: "Engineering of oil and gas extraction" },
    { word: "automotive", hint: "Engineering of cars and vehicles" },
    { word: "mechatronics", hint: "Combination of mechanical and electronics engineering" },
  
    // Engineering Concepts & Principles
    { word: "thermodynamics", hint: "Study of heat, energy, and work" },
    { word: "mechanics", hint: "Study of forces and motion" },
    { word: "fluid mechanics", hint: "Study of fluids in motion and rest" },
    { word: "statics", hint: "Study of forces in equilibrium" },
    { word: "dynamics", hint: "Study of forces causing motion" },
    { word: "kinematics", hint: "Study of motion without considering forces" },
    { word: "kinetics", hint: "Study of motion considering forces" },
    { word: "momentum", hint: "Product of mass and velocity" },
    { word: "force", hint: "Push or pull acting on an object" },
    { word: "torque", hint: "Rotational force" },
    { word: "stress", hint: "Force per unit area within materials" },
    { word: "strain", hint: "Deformation in materials under stress" },
    { word: "elasticity", hint: "Ability of a material to return to original shape" },
    { word: "plasticity", hint: "Permanent deformation of a material" },
    { word: "fracture", hint: "Breakage of a material due to stress" },
    { word: "fatigue", hint: "Material weakening under repeated stress" },
    { word: "vibration", hint: "Oscillating motion of a system" },
    { word: "resonance", hint: "Amplified vibrations at a natural frequency" },
    { word: "hydraulics", hint: "Use of liquid pressure for force transmission" },
    { word: "pneumatics", hint: "Use of compressed air for motion" },
    { word: "heat transfer", hint: "Process of heat moving between substances" },
    { word: "conduction", hint: "Heat transfer through solids" },
    { word: "convection", hint: "Heat transfer through fluids" },
    { word: "radiation", hint: "Heat transfer through electromagnetic waves" },
    { word: "entropy", hint: "Measure of disorder in a system" },
    { word: "work", hint: "Force applied over a distance" },
    { word: "power", hint: "Rate at which work is done" },
    { word: "efficiency", hint: "Ratio of useful work to input energy" },
  
    // Civil Engineering & Structural Concepts
    { word: "beam", hint: "Structural element resisting bending" },
    { word: "truss", hint: "Triangular framework for structural support" },
    { word: "girder", hint: "Large beam supporting structures" },
    { word: "load", hint: "Force acting on a structure" },
    { word: "dead load", hint: "Permanent weight of a structure" },
    { word: "live load", hint: "Variable weight from occupants and objects" },
    { word: "foundation", hint: "Base of a structure distributing loads" },
    { word: "reinforced concrete", hint: "Concrete strengthened with steel" },
    { word: "asphalt", hint: "Material used for road surfaces" },
    { word: "bridge", hint: "Structure spanning obstacles like rivers" },
    { word: "tunnel", hint: "Underground passageway" },
    { word: "earthquake engineering", hint: "Designing structures to withstand seismic activity" },
  
    // Electrical & Electronics Engineering
    { word: "voltage", hint: "Electrical potential difference" },
    { word: "current", hint: "Flow of electric charge" },
    { word: "resistance", hint: "Opposition to electric current" },
    { word: "capacitance", hint: "Ability to store electrical charge" },
    { word: "inductance", hint: "Ability to store energy in a magnetic field" },
    { word: "semiconductor", hint: "Material used in electronic circuits" },
    { word: "transistor", hint: "Electronic switch or amplifier" },
    { word: "diode", hint: "Allows current to flow in one direction" },
    { word: "oscillator", hint: "Generates continuous wave signals" },
    { word: "rectifier", hint: "Converts AC to DC" },
    { word: "microcontroller", hint: "Compact integrated circuit for automation" },
  
    // Computer & Software Engineering
    { word: "algorithm", hint: "Step-by-step procedure for solving a problem" },
    { word: "data structure", hint: "Organized format for storing data" },
    { word: "object-oriented", hint: "Programming paradigm based on objects" },
    { word: "machine learning", hint: "AI that improves from experience" },
    { word: "cloud computing", hint: "On-demand computing over the internet" },
    { word: "encryption", hint: "Securing data through encoding" },
    { word: "database", hint: "Organized collection of data" },
    { word: "cybersecurity", hint: "Protecting systems from cyber threats" },
  
    // Materials Science & Manufacturing
    { word: "alloy", hint: "Mixture of metals for enhanced properties" },
    { word: "ceramics", hint: "Inorganic, non-metallic solid materials" },
    { word: "polymer", hint: "Large molecules used in plastics and rubbers" },
    { word: "composite", hint: "Material made of two or more components" },
    { word: "welding", hint: "Process of joining metals by heat" },
    { word: "casting", hint: "Pouring liquid metal into molds" },
    { word: "3D printing", hint: "Additive manufacturing process for prototypes" },
  
    // Aerospace & Automotive Engineering
    { word: "aerodynamics", hint: "Study of air movement around objects" },
    { word: "drag", hint: "Resistance force acting against motion" },
    { word: "lift", hint: "Upward force on a wing or airfoil" },
    { word: "propulsion", hint: "Mechanism for moving vehicles forward" },
    { word: "combustion", hint: "Burning of fuel for energy" },
    { word: "fuel cell", hint: "Device that generates electricity from fuel" },
    { word: "turbocharger", hint: "Device increasing engine efficiency" },
    { word: "electric vehicle", hint: "Car powered by electricity instead of fuel" },
  ],
  business: [
    // Core Business Disciplines
    { word: "marketing", hint: "Promoting and selling products" },
    { word: "management", hint: "Overseeing and directing business operations" },
    { word: "finance", hint: "Managing money and investments" },
    { word: "investment", hint: "Allocating resources for future gains" },
    { word: "banking", hint: "Managing financial transactions" },
    { word: "accounting", hint: "Recording financial transactions" },
    { word: "real estate", hint: "Property sales and management" },
    { word: "entrepreneurship", hint: "Starting and running a business" },
    { word: "economics", hint: "Study of production, consumption, and trade" },
    { word: "supply chain", hint: "Managing product flow from production to customer" },
    { word: "human resources", hint: "Managing employees and workplace culture" },
    { word: "e-commerce", hint: "Buying and selling online" },
    { word: "insurance", hint: "Protecting against financial risks" },
    { word: "consulting", hint: "Providing expert business advice" },
  
    // Marketing & Advertising
    { word: "branding", hint: "Creating a unique business identity" },
    { word: "SEO", hint: "Optimizing web content for search engines" },
    { word: "content marketing", hint: "Promoting business through valuable content" },
    { word: "social media", hint: "Using platforms for business promotion" },
    { word: "advertising", hint: "Paid promotions for products and services" },
    { word: "public relations", hint: "Managing business reputation and media" },
    { word: "lead generation", hint: "Attracting potential customers" },
    { word: "conversion rate", hint: "Percentage of visitors who take desired action" },
    { word: "market research", hint: "Analyzing customer needs and competition" },
    { word: "demographics", hint: "Statistical data on customer groups" },
  
    // Finance & Investment
    { word: "capital", hint: "Money or assets used for investment" },
    { word: "cash flow", hint: "Money moving in and out of a business" },
    { word: "liquidity", hint: "Ability to convert assets into cash" },
    { word: "equity", hint: "Ownership value in a business" },
    { word: "assets", hint: "Resources owned by a business" },
    { word: "liabilities", hint: "Debts and obligations of a business" },
    { word: "stocks", hint: "Shares representing business ownership" },
    { word: "bonds", hint: "Fixed-income investment in a company or government" },
    { word: "mutual funds", hint: "Investment pooling money from multiple investors" },
    { word: "cryptocurrency", hint: "Digital currency using blockchain" },
    { word: "dividends", hint: "Profits paid to shareholders" },
    { word: "ROI", hint: "Return on Investment - profitability measure" },
    { word: "inflation", hint: "Increase in prices over time" },
    { word: "recession", hint: "Economic decline in a country" },
    { word: "GDP", hint: "Gross Domestic Product - economic performance measure" },
  
    // Business Operations & Strategy
    { word: "business model", hint: "Plan for generating revenue" },
    { word: "scalability", hint: "Business ability to grow and expand" },
    { word: "innovation", hint: "Creating new products or services" },
    { word: "disruption", hint: "Radical change in an industry" },
    { word: "competitive advantage", hint: "Unique strength over competitors" },
    { word: "customer service", hint: "Providing support to clients" },
    { word: "outsourcing", hint: "Hiring third parties for business functions" },
    { word: "franchise", hint: "Business model licensing brand and operations" },
    { word: "negotiation", hint: "Reaching agreements in business" },
    { word: "procurement", hint: "Acquiring goods and services for a company" },
    { word: "partnership", hint: "Business owned by two or more people" },
    { word: "merger", hint: "Combining two businesses into one" },
    { word: "acquisition", hint: "One company buying another" },
  
    // Accounting & Taxes
    { word: "bookkeeping", hint: "Recording daily business transactions" },
    { word: "balance sheet", hint: "Statement of assets and liabilities" },
    { word: "profit and loss", hint: "Financial statement showing earnings" },
    { word: "budgeting", hint: "Planning business finances" },
    { word: "audit", hint: "Examination of financial records" },
    { word: "taxation", hint: "Government levies on income and business" },
    { word: "VAT", hint: "Value Added Tax on goods and services" },
    { word: "IRS", hint: "Internal Revenue Service - tax authority" },
    { word: "GAAP", hint: "Generally Accepted Accounting Principles" },
  
    // Real Estate & Property Investment
    { word: "mortgage", hint: "Loan for buying property" },
    { word: "appraisal", hint: "Valuation of property" },
    { word: "rental income", hint: "Earnings from leasing property" },
    { word: "foreclosure", hint: "Lender reclaiming property for unpaid debt" },
    { word: "property management", hint: "Overseeing real estate operations" },
    { word: "home equity", hint: "Market value of a property minus debt" },
    { word: "landlord", hint: "Owner renting out property" },
    { word: "tenant", hint: "Person renting a property" },
    { word: "zoning", hint: "Government land-use regulations" },
    { word: "commercial real estate", hint: "Property used for business purposes" },
  
    // Entrepreneurship & Startups
    { word: "startup", hint: "Newly founded business" },
    { word: "venture capital", hint: "Funding for high-growth startups" },
    { word: "bootstrapping", hint: "Starting a business with personal funds" },
    { word: "angel investor", hint: "Wealthy individual funding startups" },
    { word: "business pitch", hint: "Presentation of a startup idea" },
    { word: "incubator", hint: "Program supporting early-stage businesses" },
    { word: "minimum viable product", hint: "Early version of a product for testing" },
    { word: "scaling", hint: "Expanding a business efficiently" },
    { word: "growth hacking", hint: "Innovative strategies for rapid business growth" },
    { word: "unicorn", hint: "Startup valued at over $1 billion" },
  
    // International Business & Trade
    { word: "globalization", hint: "Expansion of businesses worldwide" },
    { word: "import", hint: "Bringing goods into a country" },
    { word: "export", hint: "Sending goods to another country" },
    { word: "tariff", hint: "Tax on imported goods" },
    { word: "exchange rate", hint: "Value of one currency compared to another" },
    { word: "foreign investment", hint: "Investing in businesses overseas" },
    { word: "outsourcing", hint: "Hiring foreign workers for business operations" },
    { word: "supply chain management", hint: "Coordinating global production and logistics" },
    { word: "multinational corporation", hint: "Company operating in multiple countries" },
  
    // Business Ethics & Corporate Social Responsibility
    { word: "corporate social responsibility", hint: "Business accountability for social impact" },
    { word: "sustainability", hint: "Business practices benefiting the environment" },
    { word: "business ethics", hint: "Moral principles in business conduct" },
    { word: "whistleblower", hint: "Person exposing unethical business practices" },
    { word: "fair trade", hint: "Ethical business ensuring fair wages and conditions" },
    { word: "green business", hint: "Company focused on environmental sustainability" },
  ],  
  cybersecurity: [
    // Core Security Concepts
    { word: "encryption", hint: "Converting data into a secure format" },
    { word: "firewall", hint: "A security system that blocks unauthorized access" },
    { word: "phishing", hint: "A cyber attack to steal user data" },
    { word: "ransomware", hint: "Malware that demands payment" },
    { word: "malware", hint: "Software designed to harm a system" },
    { word: "authentication", hint: "Verifying a user's identity" },
    { word: "penetration testing", hint: "Simulating cyberattacks to find vulnerabilities" },
    { word: "vulnerability", hint: "Weakness in a system's security" },
    { word: "zero-day", hint: "A security flaw exploited before a fix is available" },
    { word: "patch", hint: "A software update that fixes security issues" },
    { word: "exploit", hint: "Code used to take advantage of vulnerabilities" },
    { word: "breach", hint: "Unauthorized access to data" },
    { word: "incident response", hint: "Handling and mitigating cyber attacks" },
    { word: "SOC", hint: "Security Operations Center - monitors cyber threats" },
  
    // Network Security
    { word: "VPN", hint: "Encrypted connection over the internet" },
    { word: "proxy", hint: "An intermediary server for security or anonymity" },
    { word: "IPS", hint: "Intrusion Prevention System" },
    { word: "IDS", hint: "Intrusion Detection System" },
    { word: "DDOS", hint: "Attack overwhelming a server with traffic" },
    { word: "packet sniffing", hint: "Capturing network data for analysis" },
    { word: "port scanning", hint: "Checking open ports on a network" },
    { word: "man-in-the-middle", hint: "Attack intercepting communication between parties" },
    { word: "ARP spoofing", hint: "Falsifying network identity to redirect traffic" },
    { word: "honeypot", hint: "A decoy system to attract cyber attackers" },
  
    // Identity & Access Management (IAM)
    { word: "MFA", hint: "Multi-Factor Authentication - adds extra security" },
    { word: "2FA", hint: "Two-Factor Authentication - using two verification steps" },
    { word: "biometrics", hint: "Security using fingerprints, face, or iris scans" },
    { word: "OAuth", hint: "Protocol for secure API authentication" },
    { word: "SAML", hint: "Security Assertion Markup Language for authentication" },
    { word: "SSO", hint: "Single Sign-On - one login for multiple services" },
    { word: "password hashing", hint: "Converting passwords into irreversible data" },
    { word: "salting", hint: "Adding random data to passwords for security" },
  
    // Malware & Threats
    { word: "trojan", hint: "Malware disguised as legitimate software" },
    { word: "spyware", hint: "Malware that secretly monitors user activity" },
    { word: "adware", hint: "Malicious software that displays unwanted ads" },
    { word: "keylogger", hint: "Software recording keystrokes to steal data" },
    { word: "botnet", hint: "Network of infected computers controlled remotely" },
    { word: "rootkit", hint: "Malware that hides deep in a system" },
    { word: "worms", hint: "Self-replicating malware spreading across networks" },
    { word: "fileless malware", hint: "Malware running in memory without files" },
  
    // Ethical Hacking & Cyber Defense
    { word: "ethical hacking", hint: "Using hacking skills to protect systems" },
    { word: "white hat", hint: "Ethical hacker protecting systems" },
    { word: "black hat", hint: "Hacker with malicious intent" },
    { word: "gray hat", hint: "Hacker who acts between ethical and unethical" },
    { word: "red team", hint: "Simulated attackers in security tests" },
    { word: "blue team", hint: "Defensive security professionals" },
    { word: "bug bounty", hint: "Reward program for finding security flaws" },
    { word: "reverse engineering", hint: "Analyzing software to find vulnerabilities" },
    { word: "social engineering", hint: "Manipulating people to gain access" },
    { word: "clickjacking", hint: "Tricking users into clicking hidden elements" },
    { word: "SQL injection", hint: "Exploiting databases with malicious queries" },
    { word: "XSS", hint: "Cross-Site Scripting attack injecting malicious scripts" },
    { word: "CSRF", hint: "Cross-Site Request Forgery attack tricking users" },
  
    // Cloud Security
    { word: "cloud security", hint: "Protecting data in cloud services" },
    { word: "IAM", hint: "Identity and Access Management for cloud users" },
    { word: "SaaS", hint: "Software as a Service - cloud-based applications" },
    { word: "PaaS", hint: "Platform as a Service - cloud-based development tools" },
    { word: "IaaS", hint: "Infrastructure as a Service - cloud computing resources" },
    { word: "container security", hint: "Securing Docker, Kubernetes environments" },
    { word: "API security", hint: "Protecting communication between software services" },
    { word: "shadow IT", hint: "Unauthorized software or services in a company" },
    { word: "BYOD", hint: "Bring Your Own Device - security risks in personal devices" },
  
    // Data Protection & Compliance
    { word: "GDPR", hint: "General Data Protection Regulation - EU privacy law" },
    { word: "HIPAA", hint: "Health data privacy law in the US" },
    { word: "SOC 2", hint: "Security compliance for service providers" },
    { word: "ISO 27001", hint: "International security standard" },
    { word: "data breach", hint: "Unauthorized exposure of sensitive data" },
    { word: "PII", hint: "Personally Identifiable Information" },
    { word: "tokenization", hint: "Replacing sensitive data with non-sensitive tokens" },
    { word: "DLP", hint: "Data Loss Prevention - protecting confidential data" },
  
    // Emerging Cybersecurity Trends
    { word: "blockchain security", hint: "Protecting decentralized systems" },
    { word: "AI in cybersecurity", hint: "Using artificial intelligence for security" },
    { word: "deepfake", hint: "AI-generated fake videos or voices" },
    { word: "IoT security", hint: "Protecting connected smart devices" },
    { word: "zero trust", hint: "Security model assuming no automatic trust" },
    { word: "quantum cryptography", hint: "Using quantum physics for encryption" },
    { word: "bug bounty", hint: "Ethical hackers getting paid for finding bugs" },
    { word: "cyber warfare", hint: "State-sponsored cyber attacks" },
    { word: "threat intelligence", hint: "Gathering data to prevent cyber attacks" },
  ],
  biology: [
    // Core Biological Sciences
    { word: "genetics", hint: "Study of heredity and DNA" },
    { word: "evolution", hint: "How species change over time" },
    { word: "ecology", hint: "Study of organisms in their environments" },
    { word: "botany", hint: "Study of plants" },
    { word: "zoology", hint: "Study of animals" },
    { word: "microbiology", hint: "Study of microscopic organisms" },
    { word: "cell biology", hint: "Study of the basic unit of life" },
    { word: "anatomy", hint: "Study of body structure" },
    { word: "physiology", hint: "Study of body functions" },
    { word: "biochemistry", hint: "Study of chemical processes in living things" },
    { word: "molecular biology", hint: "Study of molecules in biological systems" },
    { word: "immunology", hint: "Study of the immune system" },
    { word: "virology", hint: "Study of viruses" },
    { word: "bacteriology", hint: "Study of bacteria" },
    { word: "mycology", hint: "Study of fungi" },
    { word: "paleontology", hint: "Study of ancient life and fossils" },
    { word: "taxonomy", hint: "Classification of living things" },
    { word: "biotechnology", hint: "Using biology for technology and industry" },
  
    // Cellular & Genetic Terms
    { word: "DNA", hint: "Molecule carrying genetic instructions" },
    { word: "RNA", hint: "Molecule involved in protein synthesis" },
    { word: "chromosome", hint: "Structure carrying genetic material" },
    { word: "mutation", hint: "Change in DNA sequence" },
    { word: "gene", hint: "Unit of heredity" },
    { word: "genome", hint: "Complete set of genetic material" },
    { word: "protein", hint: "Molecule essential for cell function" },
    { word: "enzyme", hint: "Protein that speeds up chemical reactions" },
    { word: "mitosis", hint: "Cell division for growth" },
    { word: "meiosis", hint: "Cell division for reproduction" },
    { word: "replication", hint: "Copying of DNA" },
    { word: "transcription", hint: "Process of making RNA from DNA" },
    { word: "translation", hint: "Process of making proteins from RNA" },
  
    // Human & Animal Biology
    { word: "nervous system", hint: "System controlling body functions" },
    { word: "circulatory system", hint: "System transporting blood and nutrients" },
    { word: "respiratory system", hint: "System for breathing and gas exchange" },
    { word: "digestive system", hint: "System breaking down food for energy" },
    { word: "endocrine system", hint: "System regulating hormones" },
    { word: "skeletal system", hint: "Bones and structures supporting the body" },
    { word: "muscular system", hint: "System controlling movement" },
    { word: "reproductive system", hint: "System responsible for reproduction" },
    { word: "immune system", hint: "System defending against disease" },
    { word: "homeostasis", hint: "Maintaining stable internal conditions" },
  
    // Plant Biology & Ecology
    { word: "photosynthesis", hint: "Process plants use to make food" },
    { word: "chlorophyll", hint: "Pigment that makes plants green" },
    { word: "stomata", hint: "Pores in leaves for gas exchange" },
    { word: "xylem", hint: "Tissue transporting water in plants" },
    { word: "phloem", hint: "Tissue transporting nutrients in plants" },
    { word: "pollination", hint: "Transfer of pollen for reproduction" },
    { word: "germination", hint: "Process of a seed growing into a plant" },
    { word: "ecosystem", hint: "Community of living organisms" },
    { word: "biome", hint: "Large area with specific climate and species" },
    { word: "food chain", hint: "Sequence of organisms consuming each other" },
    { word: "trophic level", hint: "Position in a food chain" },
    { word: "biodiversity", hint: "Variety of life in an ecosystem" },
    { word: "symbiosis", hint: "Close relationship between different species" },
    { word: "parasitism", hint: "One organism benefits, another is harmed" },
    { word: "mutualism", hint: "Both organisms benefit" },
    { word: "commensalism", hint: "One organism benefits, the other is unaffected" },
    { word: "carbon cycle", hint: "Process of carbon moving through ecosystems" },
    { word: "nitrogen cycle", hint: "Process of nitrogen moving through ecosystems" },
  
    // Evolution & Adaptation
    { word: "natural selection", hint: "Process of survival of the fittest" },
    { word: "survival of the fittest", hint: "Best adapted organisms reproduce" },
    { word: "speciation", hint: "Formation of new species" },
    { word: "adaptation", hint: "Traits helping survival" },
    { word: "mutation", hint: "Genetic change leading to diversity" },
    { word: "genetic drift", hint: "Random changes in population genetics" },
    { word: "gene flow", hint: "Movement of genes between populations" },
    { word: "fossil", hint: "Preserved remains of ancient life" },
    { word: "extinction", hint: "Disappearance of a species" },
  
    // Microbiology & Medicine
    { word: "pathogen", hint: "Microorganism causing disease" },
    { word: "bacteria", hint: "Single-celled organisms" },
    { word: "virus", hint: "Non-living infectious agent" },
    { word: "antibiotic", hint: "Medicine killing bacteria" },
    { word: "vaccine", hint: "Substance stimulating immunity" },
    { word: "antibody", hint: "Protein defending against disease" },
    { word: "white blood cells", hint: "Cells fighting infection" },
    { word: "stem cells", hint: "Cells that can develop into different types" },
    { word: "hormone", hint: "Chemical messenger in the body" },
    { word: "metabolism", hint: "Chemical reactions in the body" },
    { word: "digestion", hint: "Breaking down food for energy" },
    { word: "osmosis", hint: "Movement of water across a membrane" },
    { word: "diffusion", hint: "Movement of molecules from high to low concentration" },
    { word: "active transport", hint: "Movement of molecules using energy" },
  
    // Cutting-Edge Biology
    { word: "CRISPR", hint: "Gene-editing technology" },
    { word: "synthetic biology", hint: "Engineering life forms" },
    { word: "cloning", hint: "Creating a genetic copy of an organism" },
    { word: "bioprinting", hint: "Using 3D printing to create biological structures" },
    { word: "stem cell therapy", hint: "Using stem cells for medical treatment" },
    { word: "personalized medicine", hint: "Custom treatments based on genetics" },
    { word: "gene therapy", hint: "Correcting defective genes" },
    { word: "bionic", hint: "Technology enhancing human biology" },
    { word: "bioinformatics", hint: "Using data science in biology" },
  ],
  medicine: [
    // Core Medical Fields
    { word: "cardiology", hint: "Study of the heart" },
    { word: "neurology", hint: "Study of the brain and nervous system" },
    { word: "oncology", hint: "Study of cancer" },
    { word: "pathology", hint: "Study of diseases" },
    { word: "immunology", hint: "Study of the immune system" },
    { word: "pharmacology", hint: "Study of drugs and their effects" },
    { word: "radiology", hint: "Medical imaging techniques" },
    { word: "anesthesiology", hint: "Study of pain management and sedation" },
    { word: "dermatology", hint: "Study of skin and its diseases" },
    { word: "pediatrics", hint: "Medical care for children" },
    { word: "geriatrics", hint: "Medical care for the elderly" },
    { word: "obstetrics", hint: "Medical care of pregnancy and childbirth" },
    { word: "gynecology", hint: "Study of the female reproductive system" },
    { word: "urology", hint: "Study of the urinary and male reproductive systems" },
    { word: "endocrinology", hint: "Study of hormones and glands" },
    { word: "nephrology", hint: "Study of kidney diseases" },
    { word: "gastroenterology", hint: "Study of the digestive system" },
    { word: "pulmonology", hint: "Study of the lungs and respiratory system" },
    { word: "orthopedics", hint: "Study of the musculoskeletal system" },
    { word: "rheumatology", hint: "Study of arthritis and autoimmune diseases" },
    { word: "hematology", hint: "Study of blood and its disorders" },
    { word: "toxicology", hint: "Study of poisons and their effects" },
    { word: "forensic medicine", hint: "Application of medicine to legal cases" },
    { word: "sports medicine", hint: "Medical care for athletes and injuries" },
  
    // Diseases & Disorders
    { word: "hypertension", hint: "High blood pressure" },
    { word: "diabetes", hint: "Disease affecting blood sugar levels" },
    { word: "stroke", hint: "Brain damage due to lack of blood flow" },
    { word: "asthma", hint: "Chronic inflammation of airways" },
    { word: "arthritis", hint: "Inflammation of the joints" },
    { word: "osteoporosis", hint: "Weakening of bones" },
    { word: "epilepsy", hint: "Neurological disorder causing seizures" },
    { word: "Alzheimer’s", hint: "Progressive memory loss disorder" },
    { word: "Parkinson’s", hint: "Neurological disorder affecting movement" },
    { word: "migraine", hint: "Severe headache disorder" },
    { word: "tuberculosis", hint: "Bacterial infection of the lungs" },
    { word: "pneumonia", hint: "Lung infection causing inflammation" },
    { word: "COVID-19", hint: "Respiratory disease caused by a coronavirus" },
    { word: "HIV/AIDS", hint: "Disease that weakens the immune system" },
    { word: "cancer", hint: "Uncontrolled growth of abnormal cells" },
    { word: "leukemia", hint: "Cancer of blood-forming tissues" },
    { word: "anemia", hint: "Lack of healthy red blood cells" },
    { word: "allergy", hint: "Immune response to harmless substances" },
    { word: "autoimmune disease", hint: "Immune system attacking the body" },
    { word: "mental illness", hint: "Disorders affecting mental health" },
    { word: "depression", hint: "Mood disorder causing persistent sadness" },
    { word: "anxiety", hint: "Disorder causing excessive worry and fear" },
    { word: "schizophrenia", hint: "Severe mental disorder affecting thoughts" },
  
    // Treatments & Procedures
    { word: "surgery", hint: "Medical operation to treat a condition" },
    { word: "chemotherapy", hint: "Cancer treatment using drugs" },
    { word: "radiotherapy", hint: "Cancer treatment using radiation" },
    { word: "dialysis", hint: "Procedure to remove waste from the blood" },
    { word: "transplant", hint: "Replacement of an organ or tissue" },
    { word: "vaccination", hint: "Injection to provide immunity" },
    { word: "antibiotic", hint: "Drug used to treat bacterial infections" },
    { word: "painkiller", hint: "Drug used to relieve pain" },
    { word: "stent", hint: "Tube placed in arteries to keep them open" },
    { word: "defibrillator", hint: "Device used to restore heart rhythm" },
    { word: "ultrasound", hint: "Imaging technique using sound waves" },
    { word: "MRI", hint: "Imaging technique using magnetic fields" },
    { word: "CT scan", hint: "Detailed imaging using X-rays" },
    { word: "biopsy", hint: "Removal of tissue for examination" },
    { word: "IV therapy", hint: "Administration of fluids via a vein" },
    { word: "CPR", hint: "Emergency procedure to revive breathing" },
    { word: "laparoscopy", hint: "Minimally invasive surgery using a camera" },
    { word: "prosthetics", hint: "Artificial limbs or body parts" },
  
    // Human Anatomy
    { word: "brain", hint: "Central organ of the nervous system" },
    { word: "heart", hint: "Organ that pumps blood" },
    { word: "lungs", hint: "Organs for breathing" },
    { word: "liver", hint: "Organ that detoxifies blood" },
    { word: "kidney", hint: "Organs that filter waste from blood" },
    { word: "stomach", hint: "Organ for digesting food" },
    { word: "intestines", hint: "Organs that absorb nutrients" },
    { word: "spinal cord", hint: "Main communication pathway in the body" },
    { word: "nerves", hint: "Fibers transmitting signals in the body" },
    { word: "muscles", hint: "Tissues enabling movement" },
    { word: "bones", hint: "Structural support for the body" },
    { word: "skin", hint: "Largest organ of the body" },
    { word: "hormones", hint: "Chemical messengers in the body" },
    { word: "blood", hint: "Fluid carrying oxygen and nutrients" },
  
    // Medical Innovations & Technology
    { word: "gene therapy", hint: "Using genes to treat diseases" },
    { word: "stem cells", hint: "Cells that can develop into any tissue" },
    { word: "nanomedicine", hint: "Medical treatments at a microscopic level" },
    { word: "robotic surgery", hint: "Use of robots in surgical procedures" },
    { word: "bioprinting", hint: "3D printing of biological tissues" },
    { word: "telemedicine", hint: "Medical consultation through digital means" },
    { word: "wearable health tech", hint: "Devices monitoring health data" },
    { word: "AI in medicine", hint: "Using artificial intelligence in healthcare" },
    { word: "precision medicine", hint: "Customized treatments based on genetics" },
    { word: "regenerative medicine", hint: "Using stem cells to repair tissues" },
    { word: "CRISPR", hint: "Gene-editing technology" },
    { word: "bionic implants", hint: "Artificial body parts with enhanced function" },
  ],
  astronomy: [
    // Fields of Astronomy
    { word: "cosmology", hint: "Study of the universe's origin and structure" },
    { word: "astrophysics", hint: "Physics of celestial objects" },
    { word: "astrobiology", hint: "Study of life in the universe" },
    { word: "heliophysics", hint: "Study of the Sun and its effects" },
    { word: "exoplanetology", hint: "Study of planets outside our solar system" },
    { word: "radio astronomy", hint: "Using radio waves to study space" },
    { word: "infrared astronomy", hint: "Using infrared light to observe celestial bodies" },
  
    // Celestial Objects
    { word: "black hole", hint: "Region where gravity prevents light from escaping" },
    { word: "neutron star", hint: "Collapsed core of a massive star" },
    { word: "white dwarf", hint: "Remnant of a low-mass star" },
    { word: "red giant", hint: "A dying star expanding in size" },
    { word: "supernova", hint: "Explosive death of a massive star" },
    { word: "quasar", hint: "A super-bright distant galaxy core" },
    { word: "pulsar", hint: "Rapidly spinning neutron star emitting beams" },
    { word: "brown dwarf", hint: "A failed star between a planet and a star" },
    { word: "exoplanet", hint: "Planet outside our solar system" },
    { word: "binary star", hint: "Two stars orbiting each other" },
    { word: "asteroid", hint: "Small rocky object in space" },
    { word: "comet", hint: "Icy body that releases gas and dust" },
    { word: "meteor", hint: "Space rock that burns up in Earth's atmosphere" },
    { word: "meteoroid", hint: "Small rock in space before entering the atmosphere" },
    { word: "meteorite", hint: "Space rock that reaches Earth's surface" },
    { word: "dwarf planet", hint: "Small celestial body, like Pluto" },
    { word: "moon", hint: "Natural satellite orbiting a planet" },
  
    // Cosmic Phenomena
    { word: "dark matter", hint: "Invisible mass affecting galaxies" },
    { word: "dark energy", hint: "Force driving the universe’s expansion" },
    { word: "gravitational wave", hint: "Ripples in spacetime from massive objects" },
    { word: "event horizon", hint: "Point of no return around a black hole" },
    { word: "accretion disk", hint: "Disk of matter spiraling into a black hole" },
    { word: "redshift", hint: "Light stretching as objects move away" },
    { word: "blueshift", hint: "Light compressing as objects move closer" },
    { word: "solar wind", hint: "Charged particles from the Sun" },
    { word: "aurora", hint: "Colorful lights from solar particles in Earth's atmosphere" },
    { word: "cosmic rays", hint: "High-energy particles from space" },
  
    // Solar System
    { word: "Mercury", hint: "Closest planet to the Sun" },
    { word: "Venus", hint: "Hottest planet in our solar system" },
    { word: "Earth", hint: "Only planet known to support life" },
    { word: "Mars", hint: "Known as the Red Planet" },
    { word: "Jupiter", hint: "Largest planet in the solar system" },
    { word: "Saturn", hint: "Planet with prominent ring system" },
    { word: "Uranus", hint: "Ice giant with a tilted axis" },
    { word: "Neptune", hint: "Farthest planet from the Sun" },
    { word: "Pluto", hint: "Dwarf planet in the Kuiper Belt" },
    { word: "Kuiper Belt", hint: "Region beyond Neptune with icy bodies" },
    { word: "Oort Cloud", hint: "Hypothetical sphere of icy objects surrounding the solar system" },
  
    // Space Exploration
    { word: "telescope", hint: "Instrument to observe distant objects" },
    { word: "satellite", hint: "Object orbiting a planet or star" },
    { word: "space probe", hint: "Unmanned spacecraft sent to explore space" },
    { word: "rover", hint: "Vehicle designed to explore planetary surfaces" },
    { word: "space station", hint: "Habitable artificial satellite in space" },
    { word: "Hubble", hint: "Famous space telescope" },
    { word: "James Webb", hint: "Advanced space telescope launched in 2021" },
    { word: "Voyager", hint: "NASA probe exploring interstellar space" },
    { word: "Apollo", hint: "NASA program that landed humans on the Moon" },
    { word: "Artemis", hint: "NASA program aiming for Moon and Mars missions" },
    { word: "Mars rover", hint: "Robotic vehicle exploring Mars" },
    { word: "SpaceX", hint: "Private space company pioneering rocket reuse" },
    { word: "Blue Origin", hint: "Private space company founded by Jeff Bezos" },
    { word: "NASA", hint: "U.S. space agency" },
    { word: "ESA", hint: "European Space Agency" },
  
    // The Universe
    { word: "Big Bang", hint: "Theory of the universe's origin" },
    { word: "multiverse", hint: "Hypothetical collection of multiple universes" },
    { word: "nebula", hint: "Cloud of gas and dust where stars form" },
    { word: "galaxy", hint: "Massive system of stars, gas, and dust" },
    { word: "Milky Way", hint: "Our home galaxy" },
    { word: "Andromeda", hint: "Closest spiral galaxy to the Milky Way" },
    { word: "supercluster", hint: "Large group of galaxies" },
    { word: "cosmic microwave background", hint: "Radiation left from the Big Bang" },
    { word: "wormhole", hint: "Hypothetical space-time shortcut" },
    { word: "time dilation", hint: "Effect of relativity on time near strong gravity" },
    { word: "space-time", hint: "Concept linking space and time in relativity" },
    { word: "interstellar", hint: "Between the stars" },
    { word: "intergalactic", hint: "Between the galaxies" },
    { word: "terraforming", hint: "Altering a planet to support life" },
    { word: "Dyson sphere", hint: "Hypothetical structure harnessing a star's energy" }
  ],        
};


export function scrambleWord(word: string): string {
  const array = word.split('');
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  const scrambled = array.join('');
  return scrambled === word ? scrambleWord(word) : scrambled;
}

export type WordEntry = { word: string; hint: string };