export const wordList = [
  { word: "typescript", hint: "A typed superset of JavaScript" },
  { word: "programming", hint: "Writing code to create software" },
  { word: "interface", hint: "A contract defining object structure" },
  { word: "developer", hint: "Someone who creates software" },
  { word: "component", hint: "A reusable piece of UI" },
  { word: "algorithm", hint: "A step-by-step procedure for solving a problem" },
  { word: "variable", hint: "A storage location identified by a name" },
  { word: "function", hint: "A block of code designed to perform a task" },
  { word: "object", hint: "An instance of a class" },
  { word: "class", hint: "A blueprint for creating objects" },
  { word: "inheritance", hint: "A mechanism for basing a class on another class" },
  { word: "encapsulation", hint: "The bundling of data with the methods that operate on that data" },
  { word: "polymorphism", hint: "The ability to present the same interface for different data types" },
  { word: "abstraction", hint: "The concept of hiding the complex reality while exposing only the necessary parts" },
  { word: "syntax", hint: "The set of rules that defines the combinations of symbols that are considered to be correctly structured programs" },
  { word: "debugging", hint: "The process of finding and fixing errors in software" },
  { word: "compilation", hint: "The process of translating source code into executable code" },
  { word: "runtime", hint: "The period during which a program is running" },
  { word: "framework", hint: "A platform for developing software applications" },
  { word: "library", hint: "A collection of precompiled routines that a program can use" },
  { word: "module", hint: "A self-contained piece of code that can be reused" },
  { word: "package", hint: "A bundle of software that can be installed and used" },
  { word: "dependency", hint: "A piece of software that another piece of software relies on" },
  { word: "version", hint: "A specific form of a software product" },
  { word: "repository", hint: "A central location where data is stored and managed" },
  { word: "commit", hint: "A record of changes made to a repository" },
  { word: "branch", hint: "A parallel version of a repository" },
  { word: "merge", hint: "The process of combining changes from different branches" },
  { word: "pull request", hint: "A request to merge changes from one branch to another" },
  { word: "continuous integration", hint: "The practice of merging all developer working copies to a shared mainline several times a day" },
  { word: "continuous deployment", hint: "The practice of automatically deploying every change that passes all stages of the production pipeline" },
  { word: "unit test", hint: "A test that covers a single 'unit' of code" },
  { word: "integration test", hint: "A test that covers multiple units of code working together" },
  { word: "end-to-end test", hint: "A test that covers the entire application from start to finish" },
  { word: "refactoring", hint: "The process of restructuring existing code without changing its external behavior" },
  { word: "philosophy", hint: "The study of the fundamental nature of knowledge, reality, and existence" },
  { word: "psychology", hint: "The scientific study of the human mind and its functions" },
  { word: "sociology", hint: "The study of the development, structure, and functioning of human society" },
  { word: "economics", hint: "The branch of knowledge concerned with the production, consumption, and transfer of wealth" },
  { word: "politics", hint: "The activities associated with the governance of a country or area" },
  { word: "history", hint: "The study of past events" },
  { word: "geography", hint: "The study of the physical features of the earth and its atmosphere" },
  { word: "literature", hint: "Written works, especially those considered of superior or lasting artistic merit" },
  { word: "art", hint: "The expression or application of human creative skill and imagination" },
  { word: "music", hint: "The art of arranging sounds in time to produce a composition" },
  { word: "theater", hint: "A building or outdoor area in which plays and other dramatic performances are given" },
  { word: "cinema", hint: "The production of movies as an art or industry" },
  { word: "architecture", hint: "The art or practice of designing and constructing buildings" },
  { word: "engineering", hint: "The application of scientific knowledge for practical purposes" },
  { word: "medicine", hint: "The science or practice of the diagnosis, treatment, and prevention of disease" },
  { word: "biology", hint: "The study of living organisms" },
  { word: "chemistry", hint: "The branch of science concerned with the substances of which matter is composed" },
  { word: "physics", hint: "The branch of science concerned with the nature and properties of matter and energy" },
  { word: "mathematics", hint: "The abstract science of number, quantity, and space" },
  { word: "astronomy", hint: "The branch of science which deals with celestial objects, space, and the physical universe" },
  { word: "geology", hint: "The science which deals with the earth's physical structure and substance" },
  { word: "meteorology", hint: "The science that deals with the phenomena of the atmosphere" },
  { word: "oceanography", hint: "The branch of science that deals with the physical and biological properties of the sea" },
  { word: "ecology", hint: "The branch of biology that deals with the relations of organisms to one another and to their physical surroundings" },
  { word: "genetics", hint: "The study of heredity and the variation of inherited characteristics" },
  { word: "anthropology", hint: "The study of human societies and cultures and their development" },
  { word: "archaeology", hint: "The study of human history and prehistory through the excavation of sites and the analysis of artifacts" },
  { word: "linguistics", hint: "The scientific study of language and its structure" },
  { word: "education", hint: "The process of receiving or giving systematic instruction" },
  { word: "pedagogy", hint: "The method and practice of teaching" },
  { word: "ethics", hint: "Moral principles that govern a person's behavior" },
  { word: "law", hint: "The system of rules that a particular country or community recognizes as regulating the actions of its members" },
  { word: "criminology", hint: "The scientific study of crime and criminals" },
  { word: "forensics", hint: "Scientific tests or techniques used in connection with the detection of crime" },
  { word: "journalism", hint: "The activity or profession of writing for newspapers, magazines, or news websites" },
  { word: "communication", hint: "The imparting or exchanging of information by speaking, writing, or using some other medium" },
  { word: "advertising", hint: "The activity or profession of producing advertisements for commercial products or services" },
  { word: "marketing", hint: "The action or business of promoting and selling products or services" },
  { word: "business", hint: "The practice of making one's living by engaging in commerce" },
  { word: "management", hint: "The process of dealing with or controlling things or people" },
  { word: "finance", hint: "The management of large amounts of money" },
  { word: "investment", hint: "The action or process of investing money for profit" },
  { word: "banking", hint: "The business conducted or services offered by a bank" },
  { word: "accounting", hint: "The process of keeping financial accounts" },
  { word: "insurance", hint: "A practice or arrangement by which a company provides a guarantee of compensation for specified loss, damage, illness, or death" },
  { word: "real estate", hint: "Property consisting of land or buildings" },
  { word: "construction", hint: "The building of something, typically a large structure" },
  { word: "transportation", hint: "The action of transporting someone or something" },
  { word: "logistics", hint: "The detailed coordination of a complex operation involving many people, facilities, or supplies" },
  { word: "hospitality", hint: "The friendly and generous reception and entertainment of guests, visitors, or strangers" },
  { word: "tourism", hint: "The commercial organization and operation of vacations and visits to places of interest" },
  { word: "agriculture", hint: "The science or practice of farming" },
  { word: "horticulture", hint: "The art or practice of garden cultivation and management" },
  { word: "forestry", hint: "The science or practice of planting, managing, and caring for forests" },
  { word: "fishing", hint: "The activity of catching fish" },
  { word: "mining", hint: "The process or industry of obtaining coal or other minerals from a mine" },
  { word: "manufacturing", hint: "The making of articles on a large scale using machinery" },
  { word: "retail", hint: "The sale of goods to the public in relatively small quantities for use or consumption" },
  { word: "wholesale", hint: "The selling of goods in large quantities to be retailed by others" },
  { word: "ecommerce", hint: "Commercial transactions conducted electronically on the internet" },
  { word: "cybersecurity", hint: "The practice of protecting systems, networks, and programs from digital attacks" },
  { word: "robotics", hint: "The branch of technology that deals with the design, construction, operation, and application of robots" },
  { word: "artificial intelligence", hint: "The simulation of human intelligence in machines" },
  { word: "machine learning", hint: "A type of artificial intelligence that allows software applications to become more accurate at predicting outcomes" },
  { word: "data science", hint: "A field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from data" },
  { word: "big data", hint: "Extremely large data sets that may be analyzed computationally to reveal patterns, trends, and associations" },
  { word: "cloud computing", hint: "The delivery of computing services over the internet" },
  { word: "internet of things", hint: "The interconnection via the internet of computing devices embedded in everyday objects" },
  { word: "blockchain", hint: "A system in which a record of transactions made in bitcoin or another cryptocurrency are maintained across several computers" },
  { word: "virtual reality", hint: "The computer-generated simulation of a three-dimensional image or environment" },
  { word: "augmented reality", hint: "An interactive experience of a real-world environment where objects are enhanced by computer-generated perceptual information" },
  { word: "quantum computing", hint: "The use of quantum-mechanical phenomena such as superposition and entanglement to perform computation" },
  { word: "nanotechnology", hint: "The branch of technology that deals with dimensions and tolerances of less than 100 nanometers" },
  { word: "biotechnology", hint: "The exploitation of biological processes for industrial and other purposes" },
  { word: "genomics", hint: "The branch of molecular biology concerned with the structure, function, evolution, and mapping of genomes" },
  { word: "neuroscience", hint: "The scientific study of the nervous system" },
  { word: "psychotherapy", hint: "The treatment of mental disorder by psychological rather than medical means" },
  { word: "nutrition", hint: "The process of providing or obtaining the food necessary for health and growth" },
  { word: "fitness", hint: "The condition of being physically fit and healthy" },
  { word: "wellness", hint: "The state of being in good health, especially as an actively pursued goal" },
  { word: "yoga", hint: "A Hindu spiritual and ascetic discipline, including breath control, simple meditation, and the adoption of specific bodily postures" },
  { word: "meditation", hint: "The practice of focusing one's mind for a period of time" },
  { word: "mindfulness", hint: "The quality or state of being conscious or aware of something" },
  { word: "spirituality", hint: "The quality of being concerned with the human spirit or soul as opposed to material or physical things" },
  { word: "religion", hint: "The belief in and worship of a superhuman controlling power" },
  { word: "philanthropy", hint: "The desire to promote the welfare of others, expressed especially by the generous donation of money to good causes" },
  { word: "volunteering", hint: "Freely offering to do something" },
  { word: "activism", hint: "The policy or action of using vigorous campaigning to bring about political or social change" },
  { word: "sustainability", hint: "The ability to be maintained at a certain rate or level" },
  { word: "conservation", hint: "The action of conserving something, in particular" },
  { word: "recycling", hint: "The action or process of converting waste into reusable material" },
  { word: "renewable energy", hint: "Energy from a source that is not depleted when used" },
  { word: "climate change", hint: "A change in global or regional climate patterns" },
] as const;

export function scrambleWord(word: string): string {
  const array = word.split('');
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  const scrambled = array.join('');
  return scrambled === word ? scrambleWord(word) : scrambled;
}
